project:
  type: book

book:
  title: "Introduction to Data Science"
  author: "Ethan Meyers"
  chapters:
    - index.qmd
    - python_basics.qmd

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  pdf:
    toc: true
    number-sections: true
    fig_caption: true




